// FILE AUTOGENERATED BY t18s
// You can safely add this to your .gitignore

/** TypeSafe translations for your Svelte app. */
declare module "$t18s" {
    import type { Writable, Readable } from 'svelte/store';

    /** The available locales */
    type Locales = ["en","de"];
    
    /** The known locales */
    export type Locale = Locales[number];
    
    /** The fallback locale that's currently in use. */
    export const fallbackLocale: "en";
    
    /** The available locales */
    export const locales : Locales;
    
    /** The current locale */
    export const locale: Writable<Locale>;
    
    /**
     * Set the current locale. Equivalent to `locale.set(newLocale)`
     * @param newLocale The new locale
     */
    export function setLocale(newLocale: Locale): void;
    
    /** Convenience function to check if something is a valid locale. */
    export const isLocale: (maybeLocale: unknown) => maybeLocale is Locale;
}

/** The messages for the domain homepage. Add messages by adding a file at /Users/sigrist/dev/t18s/site/src/translations with the name homepage.[locale].yaml */
declare module "$t18s/messages/homepage" {
    import type { Readable } from 'svelte/store';

    export const title: Readable<(values?: undefined) => string>;
    
    export const mission_statement: Readable<(values?: undefined) => string>;
    
    export const get_started_cta: Readable<(values?: undefined) => string>;
    
    export const typesafety_feature_title: Readable<(values?: undefined) => string>;
    
    export const typesafety_feature_description: Readable<(values?: undefined) => string>;
    
    export const precompilation_feature_title: Readable<(values?: undefined) => string>;
    
    export const precompilation_feature_description: Readable<(values?: undefined) => string>;
}

/** The messages for the domain . Add messages by adding a file at /Users/sigrist/dev/t18s/site/src/translations with the name .[locale].yaml */
declare module "$t18s/messages" {
    import type { Readable } from 'svelte/store';

    export const test: Readable<(values?: undefined) => string>;
}

/** The messages for the domain nav. Add messages by adding a file at /Users/sigrist/dev/t18s/site/src/translations with the name nav.[locale].yaml */
declare module "$t18s/messages/nav" {
    import type { Readable } from 'svelte/store';

    export const greeting: Readable<(values : {fullName: string}) => string>;
}

/** The messages for the domain seo. Add messages by adding a file at /Users/sigrist/dev/t18s/site/src/translations with the name seo.[locale].yaml */
declare module "$t18s/messages/seo" {
    import type { Readable } from 'svelte/store';

    export const title: Readable<(values : {pageTitle: string}) => string>;
    
    export const defaultTitle: Readable<(values?: undefined) => string>;
    
    export const unused: Readable<(values?: undefined) => string>;
}